databases:
  - name: josue
    databaseName: josue
    user: josue

services:
  - type: web
    name: E-Market
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: josue
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false